### ISSUE TITLE
Building the theme started to fail with 6.11.5

### ISSUE THREAD

**Issue by juanpin-humane** [InseeFrLab/keycloakify#243]
Seems like the zipping portion broke.

```
🔏 Building the keycloak theme...⌚
🫶 Let keycloakify do its thang
node:events:491
      throw er; // Unhandled 'error' event
      ^

ReferenceError: Blob is not defined
    at utf8size (/workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:58:5)
    at localHeader (/workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:67:24)
    at /workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:183:20
    at step (/workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:33:23)
    at Object.next (/workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:14:53)
    at /workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:4:12)
    at writeDir (/workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:174:45)
    at /workspaces/center-web/node_modules/.pnpm/keycloakify@6.11.5_3stiutgnnbnfnf3uowm5cip22i/node_modules/keycloakify/bin/tools/zip.js:233:42
Emitted 'error' event on Transform instance at:
    at Transform.onerror (node:internal/streams/readable:773:14)
    at Transform.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by garronej** [comment]
Hello @juanpin-humane,  
Sorry about this, we'll investigate.  
In the meantime you can rollback to using maven with:  

`package.json`
```json
"keycloakify": {
    "bundler": "mvn"
}
```

https://docs.keycloakify.dev/build-options#keycloakify.bundler  


Could you by any hance produce a reproduction path?  
That would help a lot.  

Hi, @lordvlad, any idea?

**Comment by juanpin-humane** [comment]
I'm going to try the latest versions to isolate exactly when did it broke and try your alternative. Thank you so much for the fast response @garronej !!!

**Comment by garronej** [comment]
You're welcome, It should be fixed in 6.11.7 :))

**Comment by lordvlad** [comment]
Hi, sorry, only now saw the message. @garronej I see that importing `Blob` resolved the issue? Looks like a nodejs version difference then? Something like in newer versions it is present in the global context, but not in an older version? @juanpin-humane can you tell which nodejs version you are using?

**Comment by juanpin-humane** [comment]
@lordvlad node 16

**Comment by juanpin-humane** [comment]
Just verified , it's fixed.

**Comment by garronej** [comment]
Thanks @juanpin-humane for taking the time to give feedback :)
