### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by aresares** [InseeFrLab/keycloakify#25]
Using Ubuntu 20

ares@ares:~/gitt/main/keycloakify-main$ sudo yarn keycloak
yarn run v1.22.10
$ yarn build && build-keycloak-theme
$ yarn clean && tsc && yarn grant-exec-perms && yarn copy-files
$ rimraf dist/
$ node dist/bin/tools/grant-exec-perms.js
$ copyfiles -u 1 src/**/*.ftl src/**/*.xml src/**/*.js dist/
🔏 Building the keycloak theme...⌚
/home/ares/gitt/main/keycloakify-main/node_modules/keycloakify/bin/tools/transformCodebase.js:66
        finally { if (e_1) throw e_1.error; }
                           ^

Error: ENOENT: no such file or directory, scandir '/home/ares/gitt/main/keycloakify-main/build'
    at Object.readdirSync (fs.js:790:3)
    at crawlRec (/home/ares/gitt/main/keycloakify-main/node_modules/keycloakify/bin/tools/crawl.js:41:39)
    at Object.crawl (/home/ares/gitt/main/keycloakify-main/node_modules/keycloakify/bin/tools/crawl.js:61:9)
    at Object.transformCodebase (/home/ares/gitt/main/keycloakify-main/node_modules/keycloakify/bin/tools/transformCodebase.js:46:40)
    at Object.generateKeycloakThemeResources (/home/ares/gitt/main/keycloakify-main/node_modules/keycloakify/bin/build-keycloak-theme/generateKeycloakThemeResources.js:69:25)
    at Object.main (/home/ares/gitt/main/keycloakify-main/node_modules/keycloakify/bin/build-keycloak-theme/build-keycloak-theme.js:50:38)
    at Object.<anonymous> (/home/ares/gitt/main/keycloakify-main/node_modules/keycloakify/bin/build-keycloak-theme/index.js:17:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by garronej** [comment]
Hi, i will need a link to the repo to help you debug

**Comment by aresares** [comment]
I'm using the source on master, the last one

**Comment by garronej** [comment]
Ah... you want to contribute? You want to build keycloakify itself?

**Comment by aresares** [comment]
No sorry my english :) I was just trying to compile the the theme on Ubuntu and I got the error above

**Comment by garronej** [comment]
No problem,  
If what you are trying to achieve is just creating a Keycloak theme then [this is the template](https://github.com/garronej/keycloakify-demo-app) you should start from.  👍🏻

**Comment by aresares** [comment]
ok thx

**Comment by noel123007** [comment]
> No problem, If what you are trying to achieve is just creating a Keycloak theme then [this is the template](https://github.com/garronej/keycloakify-demo-app) you should start from. 👍🏻

I tried building the same template. I still get the same error. I am on Windows OS @garronej 
The only change I have done is remove the `homepage` in `package.json` file. Regardless I get the error. 
Any other requirements required, like platform etc?

**Comment by garronej** [comment]
hi @noel123007 
[To build on windows you need wsl](https://github.com/InseeFrLab/keycloakify/issues/23#issuecomment-882722230)
