### ISSUE TITLE
Can't test theme on a real Keycloak instance

### ISSUE THREAD

**Issue by omar-zahid** [InseeFrLab/keycloakify#261]
Steps to reproduce:

``` bash
yarn
yarn build-keycloak-theme
```
Followed by instructions in the terminal

``` bash
Once your container is up and running: 
- Log into the admin console 👉 http://localhost:8080/admin username: admin, password: admin 👈
- Create a realm named "myrealm"
- Create a client with ID: "myclient", "Root URL": "https://www.keycloak.org/app/" and "Valid redirect URIs": "https://www.keycloak.org/app/*"
- Select Login Theme: keycloakify-starter (don't forget to save at the bottom of the page)
- Go to 👉 https://www.keycloak.org/app/ 👈 Click "Save" then "Sign in". You should see your login page

Video demoing this process: https://youtu.be/N3wlBoH4hKg
```

Logging in results in a blank page with the following error:

``` log
react-dom.production.min.js:186 
        
       Error: Missing foo in URL when redirecting to login page
    at p (valuesTransferredOverUrl.ts:117:15)
    at valuesTransferredOverUrl.ts:16:31
    at valuesTransferredOverUrl.ts:14:20
    at 7338 (valuesTransferredOverUrl.ts:9:46)
    at t (bootstrap:19:32)
    at 5872 (5872.59f1770e.chunk.js:1:5217)
    at Function.t (bootstrap:19:32)
ii @ react-dom.production.min.js:186
react-dom.production.min.js:282 
        
       Uncaught Error: Missing foo in URL when redirecting to login page
    at p (valuesTransferredOverUrl.ts:117:15)
    at valuesTransferredOverUrl.ts:16:31
    at valuesTransferredOverUrl.ts:14:20
    at 7338 (valuesTransferredOverUrl.ts:9:46)
    at t (bootstrap:19:32)
    at 5872 (5872.59f1770e.chunk.js:1:5217)
    at Function.t (bootstrap:19:32)
```

**Comment by omar-zahid** [comment]
By default, `valuesTransferredOverUrl` is called. Closing this issue.

**Comment by garronej** [comment]
Thanks, I should probably comment this by default.
