### ISSUE TITLE
Unable to launch on Apple M1

### ISSUE THREAD

**Issue by Alejandro-J-Caputto** [InseeFrLab/keycloakify#43]
Hello, 

I have build a Keycloak theme but when I try to launch the docker container I am facing the following issues (see below). Do you know how could I solve this problem? Thank you  

`09:31:08,790 ERROR [org.jboss.modcluster] (ServerService Thread Pool -- 60) MODCLUSTER000034: Failed to start advertise listener: java.net.SocketException: Protocol not available (Error setting socket option)
	at java.base/java.net.PlainDatagramSocketImpl.socketSetOption0(Native Method)
	at java.base/java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:91)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:352)
	at java.base/java.net.MulticastSocket.setInterface(MulticastSocket.java:477)
	at org.jboss.mod_cluster.core@1.4.1.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.init(AdvertiseListenerImpl.java:151)
	at org.jboss.mod_cluster.core@1.4.1.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.start(AdvertiseListenerImpl.java:161)
	at org.jboss.mod_cluster.core@1.4.1.Final//org.jboss.modcluster.ModClusterService.init(ModClusterService.java:165)
	at org.wildfly.mod_cluster.undertow@20.0.1.Final//org.wildfly.mod_cluster.undertow.UndertowEventHandlerAdapterService.start(UndertowEventHandlerAdapterService.java:83)
	at org.wildfly.clustering.service@20.0.1.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)`

**Comment by garronej** [comment]
Hi @Alejandro-J-Caputto,  
I don't have a M1 yet. (Soon though, the new MBP are out 😃)  
I'll try on a colleague's MacBook when I get the chance.  
In the meantime your don't necessarily have to build on your desktop you can do it in the CI pipeline.

**Comment by eduardosanzb** [comment]
@garronej I build keycloak v15 for M1 if you need it!

https://hub.docker.com/r/eduardosanzb/keycloak/tags

**Comment by Alejandro-J-Caputto** [comment]
Thank you for taking your time to answer. I am working again with keycloak and of course using keycloakify 😄 . Amazing job!! It rocks 🚀

**Comment by garronej** [comment]
Sorry I just ordered a new MacBook now so I didn't get the chance to test on M1 but I will eventually and address any problem that might arise.

**Comment by garronej** [comment]
I reopen, now that I got an M1 I'll try to make it work out of the box.

**Comment by garronej** [comment]
Works out of the box now. Thank you @eduardosanzb 🙏🏻

**Comment by garronej** [comment]
@eduardosanzb @Alejandro-J-Caputto.  

I need your help 🙏🏻 

I can't make it work on my M1. 

https://user-images.githubusercontent.com/6702424/162444652-da0aa229-6e6a-4338-8d96-1c8cbb4e6566.mov

I get this 404, I can't figure out why.  

How did you make it work?  

The last version, when you run `yarn keycloak` on a M1 uses `eduardosanzb/keycloak` docker image.  

Could you try and tell me if it works on your machine, maybe with [keycloakify_demo_app](https://github.com/garronej/keycloakify-demo-app)?  

I am stuck, I can't spend a whole day debugging this and, in the meantime, I can't deal with new issues coming up (#86 #85)  

If you could give me a hand on this, it would be highly appreciated!

**Comment by garronej** [comment]
Ok I found a solution 😄

**Comment by garronej** [comment]
Full M1 compat in 4.7.4
