### ISSUE TITLE
Error when executing "keycloak" script

### ISSUE THREAD

**Issue by MichaelJHaywood** [InseeFrLab/keycloakify#89]
I've cloned the `keycloakify-demo-app` from https://github.com/garronej/keycloakify-demo-app. 

I can successfully run `build` and `start` and can view the webpage. If I run `keycloak` I get this exception:

	$ yarn run keycloak
	yarn run v1.22.17
	$ yarn build && build-keycloak-theme
	$ react-scripts build
	Creating an optimized production build...
	Compiled successfully.

	File sizes after gzip:

	  202.88 kB  build\static\js\main.28f5cee3.js
	  590 B      build\static\css\main.7a0ce695.css

	The project was built assuming it is hosted at /.
	You can control this with the homepage field in your package.json.

	The build folder is ready to be deployed.
	You may serve it with a static server:

	  yarn global add serve
	  serve -s build

	Find out more about deployment here:

	  https://cra.link/deployment

	🔏 Building the keycloak theme...⌚
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
									 Dload  Upload   Total   Spent    Left  Speed
	100   132  100   132    0     0    790      0 --:--:-- --:--:-- --:--:--   795
	100 34.8M  100 34.8M    0     0  10.5M      0  0:00:03  0:00:03 --:--:-- 12.8M
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
									 Dload  Upload   Total   Spent    Left  Speed
	100   132  100   132    0     0    950      0 --:--:-- --:--:-- --:--:--   956
	100 34.8M  100 34.8M    0     0  6547k      0  0:00:05  0:00:05 --:--:-- 7221k
	C:\Users\<name>\IdeaProjects\keycloakify-demo-app\node_modules\keycloakify\bin\tools\transformCodebase.js:70
			finally { if (e_1) throw e_1.error; }
							   ^

	Error: ENOENT: no such file or directory, scandir 'C:\Users\<name>\IdeaProjects\keycloakify-demo-app\build_keycloak\src\main\resources\theme\keycloakify-demo-app\tmp_xxKdLpdIdLd\keycloak\login\resources'
		at Object.readdirSync (node:fs:1390:3)
		at crawlRec (C:\Users\<name>\IdeaProjects\keycloakify-demo-app\node_modules\keycloakify\bin\tools\crawl.js:41:39)
		at crawl (C:\Users\<name>\IdeaProjects\keycloakify-demo-app\node_modules\keycloakify\bin\tools\crawl.js:61:9)
		at transformCodebase (C:\Users\<name>\IdeaProjects\keycloakify-demo-app\node_modules\keycloakify\bin\tools\transformCodebase.js:48:50)
		at generateKeycloakThemeResources (C:\Users\<name>\IdeaProjects\keycloakify-demo-app\node_modules\keycloakify\bin\build-keycloak-theme\generateKeycloakThemeResources.js:124:51)
		at main (C:\Users\<name>\IdeaProjects\keycloakify-demo-app\node_modules\keycloakify\bin\build-keycloak-theme\build-keycloak-theme.js:58:73)
		at Object.<anonymous> (C:\Users\<name>\IdeaProjects\keycloakify-demo-app\node_modules\keycloakify\bin\build-keycloak-theme\index.js:17:37)
		at Module._compile (node:internal/modules/cjs/loader:1101:14)
		at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
		at Module.load (node:internal/modules/cjs/loader:981:32) {
	  errno: -4058,
	  syscall: 'scandir',
	  code: 'ENOENT',
	  path: 'C:\\Users\\<name>\\IdeaProjects\\keycloakify-demo-app\\build_keycloak\\src\\main\\resources\\theme\\keycloakify-demo-app\\tmp_xxKdLpdIdLd\\keycloak\\login\\resources'
	}
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

What could be causing this?

**Comment by garronej** [comment]
Hi,  
> What could be causing this?

<img width="451" alt="image" src="https://user-images.githubusercontent.com/6702424/164199590-49f8cd35-9f3b-4b95-af4d-caee67c0842d.png">

https://github.com/InseeFrLab/keycloakify#requirements

Best regards
